apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEEgaDJhPgV0p3pJX8zuobSLIAb+d+1r1yLKSP3o58Qws4Dyosl5+g7rpcjCayjkByStuHEeiBGVZfWTLDrv6IsaG6RNV1aMT3vuI7PLrhsi+nm/3escgea0GxM6KSh5N6YN3rEINs7Fb9br7NqKl1lPoY/CRashW36wcczasnAsg8AZ8XDoZ58yyjeysz3qDN2erMI4Sgfr0eOrqB5m6ONDOP4BNess5he+9rOnS5kc5KResxggZRgsoyV41Qq0ZqNRTmFMPD0EkHo3CP1l6IbGUMK8NSK0BEc/DKOCO9/UFMi1BQsH5eNHoMSl8cgUwU6MQbONPRu0XWdkEX6Mm/8erpWDcG5bY07lLu3gtC7A=